# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\1attendance.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 811)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 130, 251, 71))
        self.label.setStyleSheet("font: 56pt \"Tw Cen MT Condensed Extra Bold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 290, 51, 61))
        self.label_2.setStyleSheet("font: 63 26pt \"Segoe UI Variable Text Semibold\";\n"
"font: 34pt \"Tw Cen MT Condensed Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-40, -10, 1531, 801))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../WhatsApp Image 2024-03-21 at 14.21.12_f1e5f27c.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 80, 331, 41))
        self.label_4.setStyleSheet("font: 87 22pt \"Segoe UI Black\";\n"
"color:rgb(255, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 270, 111, 21))
        self.label_5.setStyleSheet("font: 18pt \"Sitka Heading\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 250, 231, 121))
        self.label_6.setStyleSheet("background-color: rgb(255, 230, 230);\n"
"border-radius:15px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 230, 281, 161))
        self.label_7.setStyleSheet("background-color:rgb(225, 175, 209);\n"
"border-radius:15px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 210, 330, 200))
        self.label_8.setStyleSheet("background-color: rgb(173, 136, 198);\n"
"border-radius:15px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\WhatsApp Image 2024-03-22 at 2.19.38 AM.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_9.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PRESENT"))
        self.label_2.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "You have been marked as"))
        self.label_5.setText(_translate("MainWindow", "YOUR SCORE"))
