# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\attemptquiz.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1429, 733)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.next_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(220, 540, 881, 31))
        self.next_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 170, 255);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.next_button.setObjectName("next_button")
        self.option4_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.option4_button.setGeometry(QtCore.QRect(890, 360, 201, 151))
        self.option4_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 123, 143);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.option4_button.setObjectName("option4_button")
        self.option3_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.option3_button.setGeometry(QtCore.QRect(670, 360, 201, 151))
        self.option3_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(223, 189, 64);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.option3_button.setObjectName("option3_button")
        self.option2_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.option2_button.setGeometry(QtCore.QRect(450, 360, 201, 151))
        self.option2_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(129, 191, 187);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.option2_button.setObjectName("option2_button")
        self.option1_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.option1_button.setGeometry(QtCore.QRect(220, 360, 201, 151))
        self.option1_button.setStyleSheet("QPushButton{\n"
"background-color:rgb(85, 85, 255);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.option1_button.setObjectName("option1_button")
        self.question_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.question_label.setGeometry(QtCore.QRect(230, 100, 871, 221))
        self.question_label.setStyleSheet("background-color:rgb(71, 12, 95);\n"
"font: 32pt \"Sitka Display\";\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: 1px solid rgb(171, 87, 255);\n"
"padding-top:120px;\n"
"padding-left:50px;")
        self.question_label.setText("")
        self.question_label.setObjectName("question_label")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 60, 971, 541))
        self.label.setStyleSheet("background-color:rgb(87, 25, 100);\n"
"border-radius:15px;\n"
"border-radius: 19px;\n"
"border: 2px solid rgb(191, 0, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(240, 370, 141, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(460, 370, 62, 14))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(690, 370, 62, 14))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(910, 370, 111, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 91, 61))
        self.label_2.setStyleSheet("\n"
"font: 200 50pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"background-color: rgba(0, 0, 0,0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -80, 1541, 811))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../WhatsApp Image 2024-03-21 at 8.13.11 PM - Copy.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.question_label.raise_()
        self.next_button.raise_()
        self.option2_button.raise_()
        self.option1_button.raise_()
        self.option4_button.raise_()
        self.option3_button.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.option4_button.setText(_translate("MainWindow", "Option 4"))
        self.option3_button.setText(_translate("MainWindow", "Option 3"))
        self.option2_button.setText(_translate("MainWindow", "Option 2"))
        self.option1_button.setText(_translate("MainWindow", "Option 1"))
        self.radioButton.setText(_translate("MainWindow", "Option 1"))
        self.radioButton_2.setText(_translate("MainWindow", "Option 2"))
        self.radioButton_3.setText(_translate("MainWindow", "Option 3"))
        self.radioButton_4.setText(_translate("MainWindow", "Option 4"))
