# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\autocode.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1324, 705)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1341, 721))
        self.label.setStyleSheet("background-color: rgb(197, 139, 159);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../402518027204.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 270, 281, 61))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"padding-left:90px;\n"
"font: 20pt \"Mongolian Baiti\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 180, 231, 61))
        self.label_3.setStyleSheet("font: 40pt \"Mongolian Baiti\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(76, 10, 37);\n"
"font: 63 20pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius:20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 350, 161, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 75 16pt \"Rockwell\";\n"
"background-color:rgb(164, 199, 255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(188, 188, 188);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "CODE:"))
        self.pushButton_2.setText(_translate("MainWindow", "BACK"))
        self.pushButton.setText(_translate("MainWindow", "send emails"))
