# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\createque.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 704)
        MainWindow.setStyleSheet("background-color: rgb(255, 224, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 1041, 581))
        self.label.setStyleSheet("background-color:rgb(87, 25, 100);\n"
"border-radius:15px;\n"
"border-radius: 12px;\n"
"border: 2px solid rgb(191, 0, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.question = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.question.setGeometry(QtCore.QRect(150, 40, 941, 281))
        self.question.setMaximumSize(QtCore.QSize(8765, 16777215))
        self.question.setStyleSheet("background-color:rgb(71, 12, 95);\n"
"font: 32pt \"Sitka Display\";\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"border: 1px solid rgb(171, 87, 255);\n"
"padding-top:120px;\n"
"padding-left:290px;\n"
"")
        self.question.setObjectName("question")
        self.ans2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ans2.setGeometry(QtCore.QRect(380, 380, 221, 191))
        self.ans2.setStyleSheet("background-color:rgb(129, 191, 187);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"padding-top:85px;\n"
"padding-left:20px;\n"
"color:rgb(255, 255, 255);")
        self.ans2.setObjectName("ans2")
        self.ans1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ans1.setGeometry(QtCore.QRect(140, 380, 231, 191))
        self.ans1.setStyleSheet("background-color:rgb(85, 85, 255);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"padding-top:85px;\n"
"padding-left:20px;\n"
"color:rgb(255, 255, 255);")
        self.ans1.setObjectName("ans1")
        self.ans3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ans3.setGeometry(QtCore.QRect(610, 380, 231, 191))
        self.ans3.setStyleSheet("background-color:rgb(223, 189, 64);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"padding-top:85px;\n"
"padding-left:20px;\n"
"color:rgb(255, 255, 255);")
        self.ans3.setObjectName("ans3")
        self.ans4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ans4.setGeometry(QtCore.QRect(850, 380, 231, 191))
        self.ans4.setStyleSheet("background-color:rgb(255, 123, 143);\n"
"font: 75 12pt \"Sitka Display\";\n"
"border-radius: 12px;\n"
"padding-top:85px;\n"
"padding-left:20px;\n"
"color:rgb(255, 255, 255);")
        self.ans4.setObjectName("ans4")
        self.savebtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(1150, 100, 121, 31))
        self.savebtn.setStyleSheet("font: 75 15pt \"Sitka Display\";\n"
"background-color:rgb(185, 87, 255);\n"
"border-radius: 8px;")
        self.savebtn.setObjectName("savebtn")
        self.savebtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.savebtn_2.setGeometry(QtCore.QRect(1150, 50, 121, 31))
        self.savebtn_2.setStyleSheet("font: 75 15pt \"Sitka Display\";\n"
"background-color:rgb(185, 87, 255);\n"
"border-radius: 8px;")
        self.savebtn_2.setObjectName("savebtn_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 71, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(197, 201,255);\n"
"font: 63 12pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 16px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(150, 390, 191, 16))
        self.radioButton.setStyleSheet("background-color:rgb(85, 85, 255);\n"
"font: 75 12pt \"Sitka Display\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(390, 390, 191, 16))
        self.radioButton_2.setStyleSheet("background-color:rgb(129, 191, 187);\n"
"font: 75 12pt \"Sitka Display\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(620, 390, 191, 16))
        self.radioButton_3.setStyleSheet("background-color:rgb(223, 189, 64);\n"
"font: 75 12pt \"Sitka Display\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(860, 390, 191, 16))
        self.radioButton_4.setStyleSheet("background-color:rgb(255, 123, 143);\n"
"font: 75 12pt \"Sitka Display\";")
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 0, 1381, 781))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 41, 51))
        self.label_3.setStyleSheet("\n"
"background-color:rgb(197, 201,255);\n"
"font: 63 19pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 16px;\n"
"padding left: 45px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.question.raise_()
        self.savebtn.raise_()
        self.savebtn_2.raise_()
        self.ans1.raise_()
        self.ans2.raise_()
        self.ans3.raise_()
        self.ans4.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.question.setPlaceholderText(_translate("MainWindow", "Type your question here "))
        self.ans2.setPlaceholderText(_translate("MainWindow", "Type answer option here"))
        self.ans1.setPlaceholderText(_translate("MainWindow", "Type answer option here"))
        self.ans3.setPlaceholderText(_translate("MainWindow", "Type answer option here"))
        self.ans4.setPlaceholderText(_translate("MainWindow", "Type answer option here"))
        self.savebtn.setText(_translate("MainWindow", "Save Questions"))
        self.savebtn_2.setText(_translate("MainWindow", "Add Questions"))
        self.pushButton.setText(_translate("MainWindow", "BACK"))
        self.radioButton.setText(_translate("MainWindow", "Pick the correct option"))
        self.radioButton_2.setText(_translate("MainWindow", "Pick the correct option"))
        self.radioButton_3.setText(_translate("MainWindow", "Pick the correct option"))
        self.radioButton_4.setText(_translate("MainWindow", "Pick the correct option"))
