# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\createquiz.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1281, 675)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1301, 891))
        self.label.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../blue-purple-abstract-background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 540, 211, 51))
        self.pushButton.setStyleSheet("font: 75 17pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 101, 81))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 290, 51, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../subject-computers.jpg"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(620, 290, 51, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../subject-career-ed-professional-development.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(700, 290, 51, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../subject-world-languages.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(780, 290, 51, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../subject-social-studies.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 460, 891, 51))
        self.label_10.setStyleSheet("\n"
"font: 40pt \"Stencil\";\n"
"color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 50, 111, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"font: 63 17pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 16px;\n"
"border:2px solid black;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 50, 171, 51))
        self.pushButton_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border:2px solid black;\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(203, 167, 179);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1050, 50, 151, 51))
        self.pushButton_3.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border:2px solid black;\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(203, 167, 179);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 140, 461, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../quizzard-high-resolution-logo-black-transparent.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(590, 420, 231, 111))
        self.label_11.setStyleSheet("\n"
"font: 65pt \"Stencil\";\n"
"color: rgb(223, 0, 3);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(820, 460, 891, 51))
        self.label_12.setStyleSheet("\n"
"font: 40pt \"Stencil\";\n"
"color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "CREATE A QUIZ"))
        self.label_10.setText(_translate("MainWindow", "What will you "))
        self.pushButton_4.setText(_translate("MainWindow", "BACK"))
        self.pushButton_2.setText(_translate("MainWindow", "My Library"))
        self.pushButton_3.setText(_translate("MainWindow", "Reports"))
        self.label_11.setText(_translate("MainWindow", "QUIZ"))
        self.label_12.setText(_translate("MainWindow", "TODAY"))
