# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\loadque.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1295, 733)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loadButton_2.setGeometry(QtCore.QRect(510, 30, 251, 51))
        self.loadButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(167, 127, 215);\n"
"font: 63 17pt \"Segoe UI Variable Display Semib\";\n"
"border-radius:20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(188, 188, 188);\n"
"}\n"
"")
        self.loadButton_2.setObjectName("loadButton_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(320, 100, 641, 391))
        self.tableWidget.setStyleSheet("font: 12pt \"Sans Serif Collection\";\n"
"background-color: rgba(0, 0, 0,0);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(980, 120, 71, 31))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.publish = QtWidgets.QPushButton(parent=self.centralwidget)
        self.publish.setGeometry(QtCore.QRect(530, 510, 231, 51))
        self.publish.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 147, 189);\n"
"    font: 63 17pt \"Segoe UI Variable Display Semib\";\n"
"border-radius:20px;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(188, 188, 188);\n"
"}\n"
"")
        self.publish.setObjectName("publish")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, -40, 1341, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../WhatsApp Image 2024-03-21 at 2.10.45 PM.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.statusLabel.raise_()
        self.label.raise_()
        self.loadButton_2.raise_()
        self.tableWidget.raise_()
        self.publish.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton_2.setText(_translate("MainWindow", "LOAD EXCEL FILE"))
        self.publish.setText(_translate("MainWindow", "SAVE QUESTIONS"))
