# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\publish.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1354, 907)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(400, 210, 431, 191))
        self.label_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 450, 331, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(142, 122, 181);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(142, 122, 181), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    font: 63 17pt \"Segoe UI Variable Display Semib\";\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(142, 122, 181);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 310, 231, 31))
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.bscore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.bscore.setGeometry(QtCore.QRect(450, 350, 331, 21))
        self.bscore.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.bscore.setObjectName("bscore")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 240, 341, 31))
        self.label_3.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"font: 63 20pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, 0, 1961, 921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../WhatsApp Image 2024-03-22 at 2.43.00 AM.jpeg"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1430, 860, 71, 31))
        self.label_12.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.excel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.excel.setGeometry(QtCore.QRect(350, 450, 201, 61))
        self.excel.setStyleSheet("QPushButton{\n"
"background-color:rgb(142, 122, 181);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(142, 122, 181), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    font: 63 17pt \"Segoe UI Variable Display Semib\";\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(142, 122, 181);\n"
"}\n"
"")
        self.excel.setObjectName("excel")
        self.label.raise_()
        self.label_16.raise_()
        self.pushButton_2.raise_()
        self.label_11.raise_()
        self.bscore.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_12.raise_()
        self.excel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "CREATE YOUR QUESTIONS"))
        self.label_11.setText(_translate("MainWindow", "BENCHMARK SCORE"))
        self.label_3.setText(_translate("MainWindow", "Great, You\'re almost done"))
        self.pushButton.setText(_translate("MainWindow", "BACK"))
        self.label_12.setText(_translate("MainWindow", "Subject"))
        self.excel.setText(_translate("MainWindow", "GOTO EXCEL"))
