# Form implementation generated from reading ui file 'screen2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1375, 704)
        MainWindow.setStyleSheet("background-color: rgb(170, 0, 127)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 50, 231, 71))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(197, 201,255);\n"
"font: 63 12pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 25px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-150, 40, 1331, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(170, 0, 127);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 260, 111, 101))
        self.label_4.setStyleSheet("background-color:rgb(255, 170, 255);\n"
"border-radius:30px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/WhatsApp Image 2024-02-27 at 1.19.48 AM.jpeg"))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 230, 171, 231))
        self.label_3.setStyleSheet("background-color: rgb(214, 219, 219);\n"
"border-radius:25px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 230, 161, 231))
        self.label_5.setStyleSheet("background-color: rgb(214, 219, 219);\n"
"border-radius:25px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 230, 181, 231))
        self.label_6.setStyleSheet("background-color: rgb(214, 219, 219);\n"
"border-radius:25px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(620, 260, 111, 101))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../Downloads/WhatsApp Image 2024-02-27 at 1.20.46 AM.jpeg"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(820, 260, 111, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../../Downloads/WhatsApp Image 2024-02-27 at 1.22.28 AM.jpeg"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 170, 271, 41))
        self.label_9.setStyleSheet("font: 87 29pt \"Bodoni MT Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 380, 121, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"font: 75 16pt \"Rockwell\";\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 380, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 75 16pt \"Rockwell\";\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 380, 161, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 75 16pt \"Rockwell\";\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.b3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(1020, 60, 201, 51))
        self.b3.setStyleSheet("QPushButton#b3{\n"
";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);\n"
"border-radius:25px;\n"
"    font: 12pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton#b3:pressed{\n"
"background-color: rgb(188, 188, 188);\n"
"}")
        self.b3.setObjectName("b3")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 60, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 87 22pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"padding-left:20px;")
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(780, 60, 221, 51))
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);\n"
"border-radius:25px;\n"
"    font: 12pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QPushButton#pushButton_5:pressed{\n"
"background-color: rgb(188, 188, 188);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 160, 661, 341))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 160, 341, 241))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 160, 651, 331))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.b3.raise_()
        self.label_10.raise_()
        self.pushButton_5.raise_()
        self.label_11.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1375, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "GO BACK TO HOME SCREEN"))
        self.label_9.setText(_translate("MainWindow", "LOGIN AS:"))
        self.pushButton_4.setText(_translate("MainWindow", "A Student"))
        self.pushButton_2.setText(_translate("MainWindow", "A teacher"))
        self.pushButton_3.setText(_translate("MainWindow", "An Administrator"))
        self.b3.setText(_translate("MainWindow", "REGISTER AS TEACHER"))
        self.label_10.setText(_translate("MainWindow", "New User? Sign up now!"))
        self.pushButton_5.setText(_translate("MainWindow", "REGISTER AS STUDENT"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
