# Form implementation generated from reading ui file 'c:\Users\durva\Downloads\mini4 (2)\mini4\signup.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1296, 1063)
        self.widget = QtWidgets.QWidget(parent=MainWindow)
        self.widget.setStyleSheet("background-color: rgb(99, 34, 64);\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.r2 = QtWidgets.QPushButton(parent=self.widget)
        self.r2.setGeometry(QtCore.QRect(770, 480, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.r2.setFont(font)
        self.r2.setStyleSheet("QPushButton#r2{\n"
"background-color:rgb(200, 160, 220);\n"
"    color:black;\n"
"border-radius:8px;\n"
"\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"border-radius:15px;\n"
"border: 1.5px solid black; \n"
"}\n"
"\n"
"QPushButton#r2:pressed{\n"
"background-color: rgb(87, 58, 255);\n"
"}")
        self.r2.setObjectName("r2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(280, 90, 741, 471))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"border: 5px solid black; \n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(330, 120, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(550, 580, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(200, 160, 220);\n"
"    color:black;\n"
"border-radius:12px;\n"
"\n"
"border-radius:15px;\n"
"border: 1.5px solid black; \n"
"\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(87, 58, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(710, 170, 261, 281))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../studentregis2.jpg"))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 50, 101, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"font: 63 17pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 25px;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 180, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(360, 360, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(360, 480, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 240, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 420, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 300, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border-bottom:1.5px solid rgba(0,0,0);\n"
"border-color: rgb(99, 34, 64);\n"
"padding-bottom:3px")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 1321, 751))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\Downloads\\mini4 (2)\\mini4\\../../WhatsApp Image 2024-03-22 at 2.19.38 AM.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.r2.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_5.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.r2.setText(_translate("MainWindow", "REGISTER"))
        self.label_3.setText(_translate("MainWindow", "STUDENT REGISTRATION"))
        self.pushButton.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_2.setText(_translate("MainWindow", "BACK"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Enter Branch"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Enter Email (College)"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Enter  PID"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Enter Phone no."))
