# Form implementation generated from reading ui file 'c:\Users\durva\OneDrive\Desktop\MINI4\studentjoin.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1193, 762)
        Form.setStyleSheet("background-color: rgb(99, 34, 64);\n"
"")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(400, 150, 711, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(70)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(145, 65, 104);\n"
"padding-left: 25px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(400, 280, 501, 181))
        self.label_2.setStyleSheet("border-radius:25px;\n"
"background-color: rgb(197, 139, 159);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(410, 300, 471, 141))
        self.label_3.setStyleSheet("border-radius:25px;\n"
"background-color: rgb(209, 147, 168);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(430, 320, 431, 101))
        self.label_4.setStyleSheet("border-radius:25px;\n"
"background-color: rgb(221, 155, 176);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(450, 340, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"padding-left:5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.joinbutton = QtWidgets.QPushButton(parent=Form)
        self.joinbutton.setGeometry(QtCore.QRect(700, 350, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.joinbutton.setFont(font)
        self.joinbutton.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(150, 48, 118);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(115, 36, 91);\n"
"}")
        self.joinbutton.setObjectName("joinbutton")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(-70, -160, 2481, 1431))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\durva\\OneDrive\\Desktop\\MINI4\\../../../Downloads/studentjoinbg.jpg"))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 111, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 139, 159);\n"
"font: 63 17pt \"Segoe UI Variable Small Semibol\";\n"
"border-radius: 16px;\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(209, 199, 199);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.joinbutton.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "QUIZZARD"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter a join code"))
        self.joinbutton.setText(_translate("Form", "Join"))
        self.pushButton.setText(_translate("Form", "BACK"))
